### ISSUE TITLE
tiff files can not be read

### ISSUE THREAD

**Issue by jjpeir** [anderskaestner/neutronimaging#1]
Dear Dr. Kaestner, 

My name is Jinn-Jer Peir. Thanks a lot for providing MuhRec. It is very helpful for the research promotion of neutron image.  I recently use it to process the NCT test in my laborotory.  But I cannot  sucefully use MuhRec to read the tiff files generated by our neutron radiography system.  I do not know why? The message is attached as the following
  
![capture20230626172127556](https://github.com/anderskaestner/neutronimaging/assets/132186720/9767ddcf-07d2-4999-a885-e5cc392c1fc7)

**Comment by anderskaestner** [comment]
Hi, can you please upload an example image? An open beam for example. Which version o muhrec are you using? Menu [Help]->[About]

Thanks,

Anders

On 27 Jun 2023, at 11:28, jjpeir ***@***.***> wrote:



Dear Dr. Kaestner,

My name is Jinn-Jer Peir. Thanks a lot for providing MuhRec. It is very helpful for the research promotion of neutron image. I recently use it to process the NCT test in my laborotory. But I cannot sucefully use MuhRec to read the tiff files generated by our neutron radiography system. I do not know why? The message is attached as the following

[capture20230626172127556]<https://user-images.githubusercontent.com/132186720/249102175-9767ddcf-07d2-4999-a885-e5cc392c1fc7.png>

**Comment by anderskaestner** [comment]
I moved the issue to https://github.com/neutronimaging/imagingsuite/issues/590

**Comment by anderskaestner** [comment]
I will not be able to look into it straight away. 

Meanwhile, you can test if it works on a more recent version at https://1drv.ms/f/s!AlKXEke3pNhrgYd_u4NK3tPFOY-DUA?e=Bq2oI0.  These are development builds. Your issue should be solved in MuhRec-Windows_build6eeb5237-20230404.zip

**Comment by jjpeir** [comment]
I use MuhRec 4.3. I will test if it works on a more recent version. Thanks.

**Comment by anderskaestner** [comment]
It will not work with your images.

A

On 27 Jun 2023, at 15:36, jjpeir ***@***.***> wrote:



I use MuhRec 4.3. I will test if it works on a more recent version. Thanks.
